[versions]
kbrig = "0.1.0"

[libraries]
adventure-bom = "net.kyori:adventure-bom:4.13.1"
brigadier = "com.mojang:brigadier:1.0.18"
kbrig-brigadier = { module = "org.anvilpowered:kbrig-brigadier", version.ref = "kbrig" }
kbrig-core = { module = "org.anvilpowered:kbrig-core", version.ref = "kbrig" }
paper = "io.papermc.paper:paper-api:1.19.4-R0.1-SNAPSHOT"
velocity = "com.velocitypowered:velocity-api:3.2.0-SNAPSHOT"

[bundles]


[plugins]
kotlin-jvm = "org.jetbrains.kotlin.jvm:1.8.20"
ktlint = "org.jlleitschuh.gradle.ktlint:11.6.1"
shadow = "com.github.johnrengelman.shadow:8.1.1"
sponge = "org.spongepowered.gradle.plugin:2.2.0"
